### ISSUE TITLE
Post reviews on Spot page

### ISSUE THREAD

**Issue by ademars94** [ademars94/surfing_app#1]
I am trying to get a list of reviews to appear on the show view for Spots.  I have declared a variable in spots_controller.rb that gets set to all of the reviews for that spot.  I also have in show.html.erb a line that should be showing at least something on my page.  No error and I'm not sure why *nothing* is happening.

![Spots Controller](https://i.imgur.com/u3hWBFU.png)
![Show View](https://i.imgur.com/lbwTaqm.png)
![Routes](https://i.imgur.com/8kHcUnt.png)

**Comment by tambling** [comment]
1. There is a far easier way to do what you do on line 9 of `SpotsController` (think about what using `has_many` gets us.

2. On line 17 of your `show.html.erb`, you can't just dump the variable in there and expect it to do something. You should say `<% @reviews.each do |review| %>` (or equivalent) and act on each review individually.

3. Are you absolutely certain that `@spot` has reviews associated with it?

**Comment by h4w5** [comment]
Sorry I can't help you right now, roping in @EARnagram

**Comment by ademars94** [comment]
@tambling Thank you, Dean!
