### ISSUE TITLE
Newly created reviews are not accessible through @spot.reviews in my Spot show page

### ISSUE THREAD

**Issue by ademars94** [ademars94/surfing_app#2]
My ```.each``` method in my *show.html.erb* page is not working properly.  If I put ```<% binding.pry %>``` at the bottom of the show page, I am able to call ```@spot.reviews``` and receive an empty array as the output.  I'm not sure why my reviews aren't being saved in that array.  They are being saved though, because I can call ```Review.all``` in the console and it returns all of the reviews.  ```@reviews``` is defined in *spots_controller.rb*

![](https://i.imgur.com/yCfUPl5.png)
![](https://i.imgur.com/HgCtN5t.png)
![](https://i.imgur.com/kTnqFfK.png)
![](https://i.imgur.com/EMuEBWs.png)
![](https://i.imgur.com/m4ngXin.png)

**Comment by tambling** [comment]
Couple of things: 1. You're calling `binding.pry` on your `show` page, before you get a chance to write or submit a review. Remove that `binding.pry`, try to submit a review, then...

2. When you post the review, open up the window with your `rails server` and see what happens. Make sure the data you expect to be passed is actually being passed. You'll be able to see the `params` hash as it was set– how does that correspond to what's being acted on in `reviews#create`? Is it even being routed to `reviews#create`?

**Comment by ademars94** [comment]
@tambling 
![](https://i.imgur.com/V5YBdMO.png)

**Comment by ademars94** [comment]
Reviews are being created, they are just not associated with a spot_id, which they should be.
