### ISSUE TITLE
Having trouble with redirect when updating a review.

### ISSUE THREAD

**Issue by ademars94** [ademars94/surfing_app#3]
### Reviews Controller
![](https://i.imgur.com/9C0OpCv.png)
I am having trouble with reviews#update.  If the review is actually updated, it should redirect.  I have been going hard on the trial and error and I am out of ideas.  Right now it redirects to (what it thinks is) the page for the newly updated review.  The problem is, I don't have that page, and I don't want that to be part of my application.  I want to redirect back to the view for spots#show, which displays all of the reviews for that spot.  Right now it is set to redirect to the ```root_path``` for troubleshooting purposes, and that isn't working either.
<br>

### The Error
![](https://i.imgur.com/zbNnDK3.png)
It's trying to go to the page for the review I just edited.
<br>

### Model Relationships
![](https://i.imgur.com/UEgi6EK.png)
![](https://i.imgur.com/4CB4vvt.png)
<br>

##### Reviews Edit View
![](https://i.imgur.com/dB2bgba.png)
##### Spots Show View
![](https://i.imgur.com/RKEZic7.png)
<br>

### Routes
![](https://i.imgur.com/Ob9dwp7.png)
<br>

### Rake Routes
![](https://i.imgur.com/e9aIdvi.png)
<br>

### Schema
![](https://i.imgur.com/7cwQhJO.png)

**Comment by EARnagram** [comment]
Yo! It looks like you don't have a route to update your review.  You need to open up your routes for an update (put/patch) method for reviews

Hope that helps!

**Comment by EARnagram** [comment]
Also, wow what a beautiful github issue - thanks so much for making this easily accessible!

**Comment by h4w5** [comment]
Good issue :+1: ! If it works, @ademars94, close it.
