### ISSUE TITLE
reviews#destroy not working

### ISSUE THREAD

**Issue by ademars94** [ademars94/surfing_app#4]
I can't figure out the correct ```link_to``` when trying to destroy a review.  ```rake routes``` shows that the destroy method is available, as I have added it to my routes file.  I think the machinery is in place for the reviews to actually be destroyed, with the exception of my ```link_to``` line (line 55).
<br>
## That Dank Erb
![](https://i.imgur.com/dsIFdGb.png)
<br>
## Destroy Method
![](https://i.imgur.com/zE1q6gu.png)

**Comment by tambling** [comment]
~~Two~~ Three things:
1. `link_to` can take options– [check out this doc](http://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to) and scroll down to `method` in "Options."

2. On line 33 in your controller, you refer to `@review` without having set it. Should probably set it first.

3. On line 35, you refer to `@review.spot` after you've putatively destroyed your `@review`. You should probably cache `@review.spot` somewhere.

**Comment by ademars94** [comment]
@tambling Thank you!  Fernando and I got it working
